name       : ruby-manpages
version    : 0.6.1
release    : 2
source     :
    - https://rubygems.org/downloads/manpages-0.6.1.gem : cdbad16823c8510c15a93d4cdbd46e7b4290aff8b10f3d4b70caa8e62c8de686
license    : MIT
component  : programming.ruby
summary    : With this gem the rubygems command will detect man pages within gems
    and exposes them to the man command.
description: |
    With this gem the rubygems command will detect man pages within gems and exposes them to the man command.
builddeps  :
    - pkgconfig(ruby-2.6)
rundeps    :
    - ruby
install    : |
    %gem_install
